# Generated by Django 5.1.2 on 2024-10-30 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_finish_date', models.DateField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('technology_stack', models.TextField(blank=True, null=True)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('size_bucket', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Very Large', 'Very Large')], max_length=20)),
                ('team_size', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Open', 'Open'), ('Mitigation', 'Mitigation'), ('Contingency', 'Contingency'), ('Closed', 'Closed'), ('Reopen', 'Reopen')], max_length=20)),
                ('impact', models.IntegerField(blank=True, default=0, null=True)),
                ('likelihood', models.IntegerField(blank=True, default=0, null=True)),
                ('escalated', models.BooleanField(blank=True, default=False, null=True)),
                ('date_identified', models.DateField(blank=True, null=True)),
                ('mitigation_plan', models.TextField(blank=True, null=True)),
                ('contingency_plan', models.TextField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('final_report', models.TextField(blank=True, null=True)),
                ('date_last_updated', models.DateField(blank=True, null=True)),
                ('date_reopened', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.prj')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
