# Generated by Django 5.1.2 on 2024-10-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_category_risk_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='approach',
            field=models.CharField(blank=True, choices=[('Reduce', 'Reduce'), ('Avoid', 'Avoid'), ('Transfer', 'Transfer'), ('Accept', 'Accept'), ('Share', 'Share')], max_length=20),
        ),
    ]
