# Generated by Django 5.1.2 on 2024-10-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_risk_approach'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='owner',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='approach',
            field=models.CharField(blank=True, choices=[('Reduce', 'Reduce'), ('Avoid', 'Avoid'), ('Transfer', 'Transfer'), ('Accept', 'Accept'), ('Share', 'Share')], max_length=10),
        ),
    ]
