# Generated by Django 5.1.2 on 2024-10-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_risk_owner_alter_risk_approach'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='first_indicator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='reason_and_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
