# Generated by Django 5.1.2 on 2024-11-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_prj_status_alter_risk_date_identified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prj',
            name='estimated_finish_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='prj',
            name='start_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='date_closed',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='date_last_updated',
            field=models.DateField(auto_now=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='date_reopened',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
    ]
